
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVCProject.Models.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Notlar
{

    public int NotId { get; set; }

    public byte DersId { get; set; }

    public int OgrId { get; set; }

    public byte Sınav1 { get; set; }

    public byte Sınav2 { get; set; }

    public byte Sınav3 { get; set; }

    public byte Proje { get; set; }

    public decimal Ortalama { get; set; }

    public bool Durum { get; set; }



    public virtual Tbl_Dersler Tbl_Dersler { get; set; }

    public virtual Tbl_Ogrenci Tbl_Ogrenci { get; set; }

}

}
